name: Pull request validator

on:
  pull_request:
    branches: [ main ]

jobs:
  golint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest


  horusec:
    name: Identify Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" -e="true"


  build:
    needs: [golint, horusec]

    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.19", "1.18", "1.17", "1.16", "1.15", "1.14", "1.13"]
    
    steps:
    - name: Clone Repository 
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.goVersion }}

    - name: Test
      run: go test -v ./...


  sonarcloud:
    needs: build

    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Run coverage
        run: |
          mkdir -p bin
          go test -short -coverprofile=bin/cov.out ./...
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
